branch-defaults:
  master:
    environment: null
    group_suffix: null
  stonkTA_AWS_branch:
    environment: stonkTA-AWS-env5
environment-defaults:
  stonkTA-AWS-env:
    branch: null
    repository: null
  stonkTA-AWS-env5:
    branch: null
    repository: null
global:
  application_name: stonkTA_AWS_app
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
